### ISSUE TITLE
Reverse proxy and Grafana dependency

### ISSUE THREAD

**Issue by nolantait** [fremantle-industries/prop#165]
Using the standard `docker compose up` leads to some sort of race condition where `grafana` host is not available when `reverse_proxy` is initializing.

The workaround is to start grafana first: `docker compose up grafana` and then `docker compose up` but the error is hard to spot in the logs and will probably be missed by most.

I suppose one way is to add grafana as a dependency to reverse_proxy but you mentioned in the last issue you wanted to keep the ability to spin them up individually. Maybe we add it to the readme? What do you suggest?

I've noticed on most other repos such as `history` that the standard `docker compose up` misses some critical setup such as migrating the database and such. I end up having to spin things up individually or start from the contributor instructions before getting it running smooth. Not 100% sure if its because of the race condition here or not.

P.S Took the last month to really dig into Elixir and I'm finally getting productive. Hoping to add some contributions soon.

I've added some notes in my UX log: https://taitventures.notion.site/Prop-User-Experience-Log-31c7daa29a8d471b86c015359e8b4e94

**Comment by rupurt** [comment]
@nolantait what OS are you using? I'm on Linux but used OS X for a long time. I eventually had to give up on OS X because `docker` is near native speed on Linux.

How long does it take for Grafana to boot? And how long does it take for all services within `docker-compose` to boot?

**Comment by nolantait** [comment]
I use [Manjaro](manjaro.org/) as my main OS (no virtual machine or anything). I actually swapped for similar reasons. They tried to force me to upgrade to Windows 11 to use my GPU in docker so I figured it was time to switch for good.

Booting is quick, looks like reverse proxy boots a little too fast if anything. Whole booting takes a few seconds and then full setup with all the migrations after a minute or so.

**Comment by rupurt** [comment]
So is the concern that it's temporarily broken?

One potential solution would be to default to what I currently have and add an extra compose file that starts all the services with dependencies. So you could then alias a command to something like this.

```bash
alias dcp="docker-compose -f docker-compose.yml -f docker-compose.with-all-dependencies.yml` 
```

**Comment by nolantait** [comment]
Well it actually leads to problems later on in the initialization process where the `web` service can't find `db` etc, eventually leading to lots of errors around the DB showing up in the console. Then after if you reboot the migrations don't run again and it leads to some confusing errors that can eventually be resolved by re-running migrations as mentioned in the readme.

Alias is fine but probably a lot to ask each person trying to mess with their configs to get things running easily. I would suggest something like a makefile maybe? This is an [example](https://github.com/jupyter/docker-stacks/blob/master/Makefile) from the Jupyter notebook docker-stacks repo. See also: [https://makefiletutorial.com/](https://makefiletutorial.com/)

```
# ./Makefile

SHELL=/bin/bash

develop:
        echo "Starting developer mode..."
        docker-compose -f docker-compose.yml

start:
	echo "Starting all services..."
        docker-compose -f docker-compose.yml -f docker-compose.with-all-dependencies.yml
```

Users would run it with `make start` or `make develop` and then you have one place to setup building different setups that can be extended without depending on user configs. Thoughts?

**Comment by rupurt** [comment]
I like the makefile idea. Can you submit a PR?

**Comment by rupurt** [comment]
@nolantait added Makefile
